version: "3.9"

networks:
  default:
    driver: bridge

volumes:
  postgres-data:
    
services:
  #### FAST ---- SERVICES ---- BEGIN ####

  #### FAST ---- SERVICES - [PART] - COLLECTOR ---- BEGIN ####
  api:
    build: ./api
    ports:
      - "8000:5000"
    networks:
      - "default"
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=5000
      - VERSION=1
      - VERSION_FULL=1.0.0000
      - DEPLOYED_PREFIX=
      - DB_HOST=postgres
      - DB_SCHEMA=mountain
      - DB_USER=user23
      - DB_PASS=pwd23
      
  postgres:
    image: postgis/postgis:15-3.3-alpine
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    networks:
      - "default"
    environment:
      - 'POSTGRES_DB=mountain'
      - 'POSTGRES_USER=user23'
      - 'POSTGRES_PASSWORD=pwd23'

